### ISSUE TITLE
Not working on Windows because of the lack of escaping

### ISSUE THREAD

**Issue by zvmsbackend** [soweli-p/FsiX#3]
`dotnet fsix` isn't working on Windows with an error reported by fsi session like this:

```
input.fsx(1,1): error FS2301: “D:\.nuget\packages
                                                 six\0.0.3     ools
et9.0ny\PrettyPrompt.dll” is not a valid assembly name
```

The assembly name should have been "D:\.nuget\packages\fsix\0.0.3\tools\net9.0ny\PrettyPrompt.dll", but `\f` `\t` and `\n` are parsed as escape sequences, leading to an ill-formed Windows path.

The problem roots in a direct interpolation in `Configuration.fs`, line 8-11:

```fsharp
let prettyPromptDll =
    typeof<PrettyPrompt.PromptConfiguration> |> _.Assembly |> _.Location

let loadDllString = $"#r \"{prettyPromptDll}\"\n"
```

A trivial solution would be as follows:

```fsharp
    typeof<PrettyPrompt.PromptConfiguration> |> _.Assembly |> _.Location |> _.Replace("\\", "\\\\")
```

**Comment by soweli-p** [comment]
Thanks for finding exact line needed to be fixed!
I dont have windows machine rn so i cannot test, but it should work with 0.0.4 when it'll be verified on nuget
